name: Daily DevOps Job Fetch

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 7 * * *"  # Every day at 1 PM IST
  workflow_dispatch:

jobs:
  fetch-and-email-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install google-genai

      - name: Run job search and email
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CSE_API_KEY: ${{ secrets.GOOGLE_CSE_API_KEY }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python scripts/daily_devops_jobs.py